// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PublishingHouse.DAL.Data;

#nullable disable

namespace PublishingHouse.DAL.Migrations
{
    [DbContext(typeof(PublishingHouseDbContext))]
    [Migration("20241204214513_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PublishingHouse.DAL.Model.BatchPrint", b =>
                {
                    b.Property<int>("BatchPrintId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("batch_print_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BatchPrintId"));

                    b.Property<int>("BookQuantity")
                        .HasColumnType("int")
                        .HasColumnName("book_quantity");

                    b.Property<DateTime?>("CreateDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("create_date_time")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("number");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<DateOnly?>("PrintDate")
                        .HasColumnType("date")
                        .HasColumnName("print_date");

                    b.Property<int>("QualityMarkId")
                        .HasColumnType("int")
                        .HasColumnName("quality_mark_id");

                    b.Property<DateTime?>("UpdateDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("update_date_time");

                    b.HasKey("BatchPrintId")
                        .HasName("PK__BatchPri__131B3A7E22864534");

                    b.HasIndex("OrderId");

                    b.HasIndex("QualityMarkId");

                    b.HasIndex(new[] { "Number" }, "UQ__BatchPri__FD291E41B1E14406")
                        .IsUnique();

                    b.ToTable("BatchPrint", (string)null);
                });

            modelBuilder.Entity("PublishingHouse.DAL.Model.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("book_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<string>("Annotation")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("annotation");

                    b.Property<string>("Author")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("author");

                    b.Property<string>("CoverImagePath")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("cover_image_path");

                    b.Property<DateTime?>("CreateDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("create_date_time")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Genre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("genre");

                    b.Property<string>("Isbn")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("isbn");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<int?>("Pages")
                        .HasColumnType("int")
                        .HasColumnName("pages");

                    b.Property<int?>("PublicationYear")
                        .HasColumnType("int")
                        .HasColumnName("publication_year");

                    b.Property<string>("Size")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("size");

                    b.Property<int?>("Sku")
                        .HasColumnType("int")
                        .HasColumnName("sku");

                    b.Property<DateTime?>("UpdateDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("update_date_time");

                    b.Property<double?>("Weight")
                        .HasColumnType("float")
                        .HasColumnName("weight");

                    b.HasKey("BookId")
                        .HasName("PK__Book__490D1AE11E94B7E0");

                    b.HasIndex(new[] { "Isbn" }, "UQ__Book__99F9D0A4745D556C")
                        .IsUnique()
                        .HasFilter("[isbn] IS NOT NULL");

                    b.HasIndex(new[] { "Sku" }, "UQ__Book__DDDF4BE78D032874")
                        .IsUnique()
                        .HasFilter("[sku] IS NOT NULL");

                    b.ToTable("Book", (string)null);
                });

            modelBuilder.Entity("PublishingHouse.DAL.Model.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("city_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<DateTime?>("CreateDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("create_date_time")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<int>("RegionId")
                        .HasColumnType("int")
                        .HasColumnName("region_id");

                    b.Property<DateTime?>("UpdateDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("update_date_time");

                    b.HasKey("CityId")
                        .HasName("PK__City__031491A848DF29EC");

                    b.HasIndex("RegionId");

                    b.HasIndex(new[] { "Name" }, "UQ__City__72E12F1B0C612C9A")
                        .IsUnique()
                        .HasFilter("[name] IS NOT NULL");

                    b.ToTable("City", (string)null);

                    b.HasData(
                        new
                        {
                            CityId = 1,
                            CreateDateTime = new DateTime(2024, 12, 4, 21, 45, 12, 652, DateTimeKind.Utc).AddTicks(8233),
                            Name = "Springfield",
                            RegionId = 1
                        },
                        new
                        {
                            CityId = 2,
                            CreateDateTime = new DateTime(2024, 12, 4, 21, 45, 12, 652, DateTimeKind.Utc).AddTicks(8943),
                            Name = "Shelbyville",
                            RegionId = 1
                        },
                        new
                        {
                            CityId = 3,
                            CreateDateTime = new DateTime(2024, 12, 4, 21, 45, 12, 652, DateTimeKind.Utc).AddTicks(8944),
                            Name = "Ogdenville",
                            RegionId = 2
                        });
                });

            modelBuilder.Entity("PublishingHouse.DAL.Model.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<DateOnly?>("AddressDate")
                        .HasColumnType("date")
                        .HasColumnName("address_date");

                    b.Property<DateTime?>("CreateDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("create_date_time")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CustomerTypeId")
                        .HasColumnType("int")
                        .HasColumnName("customer_type_id");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdateDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("update_date_time");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("user_id");

                    b.HasKey("CustomerId")
                        .HasName("PK__Customer__CD65CB850C221190");

                    b.HasIndex("CustomerTypeId");

                    b.HasIndex(new[] { "Email" }, "UQ__Customer__AB6E6164FBEB906C")
                        .IsUnique()
                        .HasFilter("[email] IS NOT NULL");

                    b.ToTable("Customer", (string)null);
                });

            modelBuilder.Entity("PublishingHouse.DAL.Model.CustomerType", b =>
                {
                    b.Property<int>("CustomerTypeId")
                        .HasColumnType("int")
                        .HasColumnName("customer_type_id");

                    b.Property<DateTime?>("CreateDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("create_date_time")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdateDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("update_date_time");

                    b.HasKey("CustomerTypeId")
                        .HasName("PK__Customer__3320C939AD7E17BD");

                    b.HasIndex(new[] { "Name" }, "UQ__Customer__72E12F1B59917A9E")
                        .IsUnique()
                        .HasFilter("[name] IS NOT NULL");

                    b.ToTable("CustomerType", (string)null);

                    b.HasData(
                        new
                        {
                            CustomerTypeId = 1,
                            CreateDateTime = new DateTime(2024, 12, 4, 21, 45, 12, 656, DateTimeKind.Utc).AddTicks(285),
                            Name = "Individual"
                        },
                        new
                        {
                            CustomerTypeId = 2,
                            CreateDateTime = new DateTime(2024, 12, 4, 21, 45, 12, 656, DateTimeKind.Utc).AddTicks(495),
                            Name = "Corporate"
                        });
                });

            modelBuilder.Entity("PublishingHouse.DAL.Model.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<DateTime?>("CreateDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("create_date_time")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("PositionId")
                        .HasColumnType("int")
                        .HasColumnName("position_id");

                    b.Property<int>("ProductionId")
                        .HasColumnType("int")
                        .HasColumnName("production_id");

                    b.Property<DateTime?>("UpdateDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("update_date_time");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("user_id");

                    b.HasKey("EmployeeId")
                        .HasName("PK__Employee__C52E0BA82065EEAB");

                    b.HasIndex("PositionId");

                    b.HasIndex("ProductionId");

                    b.HasIndex(new[] { "UserId" }, "UQ__Employee__B9BE370E4E2C7666")
                        .IsUnique()
                        .HasFilter("[user_id] IS NOT NULL");

                    b.ToTable("Employee", (string)null);
                });

            modelBuilder.Entity("PublishingHouse.DAL.Model.OrderBook", b =>
                {
                    b.Property<int>("OrderBooksId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("order_books_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderBooksId"));

                    b.Property<int>("BookId")
                        .HasColumnType("int")
                        .HasColumnName("book_id");

                    b.Property<int>("BookQuantity")
                        .HasColumnType("int")
                        .HasColumnName("book_quantity");

                    b.Property<DateTime?>("CreateDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("create_date_time")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<DateTime?>("UpdateDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("update_date_time");

                    b.HasKey("OrderBooksId")
                        .HasName("PK__OrderBoo__6F7F4BB716436A2F");

                    b.HasIndex("BookId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderBooks");
                });

            modelBuilder.Entity("PublishingHouse.DAL.Model.OrderRequest", b =>
                {
                    b.Property<int>("OrderRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("order_request_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderRequestId"));

                    b.Property<string>("AuthorName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("author_name");

                    b.Property<string>("BookName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("book_name");

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("completion_date");

                    b.Property<string>("CoverImagePath")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("cover_image_path");

                    b.Property<string>("CoverType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("cover_type");

                    b.Property<DateTime?>("CreateDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("create_date_time")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<string>("FasteningType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("fastening_type");

                    b.Property<string>("Genre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("genre");

                    b.Property<bool?>("IsLaminated")
                        .HasColumnType("bit")
                        .HasColumnName("is_laminated");

                    b.Property<string>("PaperType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("paper_type");

                    b.Property<string>("PrintType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("print_type");

                    b.Property<int>("PublicationYear")
                        .HasColumnType("int")
                        .HasColumnName("publication_year");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<DateTime?>("UpdateDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("update_date_time");

                    b.HasKey("OrderRequestId");

                    b.HasIndex("CustomerId");

                    b.ToTable("OrderRequest", (string)null);
                });

            modelBuilder.Entity("PublishingHouse.DAL.Model.OrderStatus", b =>
                {
                    b.Property<int>("OrderStatusId")
                        .HasColumnType("int")
                        .HasColumnName("order_status_id");

                    b.Property<DateTime?>("CreateDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("create_date_time")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdateDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("update_date_time");

                    b.HasKey("OrderStatusId")
                        .HasName("PK__OrderSta__A499CF2325C121F2");

                    b.HasIndex(new[] { "Name" }, "UQ__OrderSta__72E12F1BA2D4DCAB")
                        .IsUnique()
                        .HasFilter("[name] IS NOT NULL");

                    b.ToTable("OrderStatus", (string)null);

                    b.HasData(
                        new
                        {
                            OrderStatusId = 1,
                            CreateDateTime = new DateTime(2024, 12, 4, 21, 45, 12, 661, DateTimeKind.Utc).AddTicks(3750),
                            Name = "Pending"
                        },
                        new
                        {
                            OrderStatusId = 2,
                            CreateDateTime = new DateTime(2024, 12, 4, 21, 45, 12, 661, DateTimeKind.Utc).AddTicks(4138),
                            Name = "Completed"
                        },
                        new
                        {
                            OrderStatusId = 3,
                            CreateDateTime = new DateTime(2024, 12, 4, 21, 45, 12, 661, DateTimeKind.Utc).AddTicks(4139),
                            Name = "Cancelled"
                        },
                        new
                        {
                            OrderStatusId = 4,
                            CreateDateTime = new DateTime(2024, 12, 4, 21, 45, 12, 661, DateTimeKind.Utc).AddTicks(4140),
                            Name = "In Progress"
                        },
                        new
                        {
                            OrderStatusId = 5,
                            CreateDateTime = new DateTime(2024, 12, 4, 21, 45, 12, 661, DateTimeKind.Utc).AddTicks(4142),
                            Name = "On Hold"
                        });
                });

            modelBuilder.Entity("PublishingHouse.DAL.Model.Position", b =>
                {
                    b.Property<int>("PositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("position_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PositionId"));

                    b.Property<DateTime?>("CreateDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("create_date_time")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdateDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("update_date_time");

                    b.HasKey("PositionId")
                        .HasName("PK__Position__99A0E7A421BDE14B");

                    b.HasIndex(new[] { "Name" }, "UQ__Position__72E12F1B62DE1B97")
                        .IsUnique()
                        .HasFilter("[name] IS NOT NULL");

                    b.ToTable("Position", (string)null);

                    b.HasData(
                        new
                        {
                            PositionId = 1,
                            CreateDateTime = new DateTime(2024, 12, 4, 21, 45, 12, 662, DateTimeKind.Utc).AddTicks(4434),
                            Name = "Manager"
                        },
                        new
                        {
                            PositionId = 2,
                            CreateDateTime = new DateTime(2024, 12, 4, 21, 45, 12, 662, DateTimeKind.Utc).AddTicks(4954),
                            Name = "Designer"
                        },
                        new
                        {
                            PositionId = 3,
                            CreateDateTime = new DateTime(2024, 12, 4, 21, 45, 12, 662, DateTimeKind.Utc).AddTicks(4956),
                            Name = "Editor"
                        },
                        new
                        {
                            PositionId = 4,
                            CreateDateTime = new DateTime(2024, 12, 4, 21, 45, 12, 662, DateTimeKind.Utc).AddTicks(4957),
                            Name = "Printer"
                        },
                        new
                        {
                            PositionId = 5,
                            CreateDateTime = new DateTime(2024, 12, 4, 21, 45, 12, 662, DateTimeKind.Utc).AddTicks(4958),
                            Name = "Binder"
                        });
                });

            modelBuilder.Entity("PublishingHouse.DAL.Model.PrintOrder", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateOnly?>("CompletionDate")
                        .HasColumnType("date")
                        .HasColumnName("completion_date");

                    b.Property<string>("CoverType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("cover_type");

                    b.Property<DateTime?>("CreateDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("create_date_time")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<string>("FasteningType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("fastening_type");

                    b.Property<bool>("IsLaminated")
                        .HasColumnType("bit")
                        .HasColumnName("is_laminated");

                    b.Property<int>("Number")
                        .HasColumnType("int")
                        .HasColumnName("number");

                    b.Property<int>("OrderStatusId")
                        .HasColumnType("int")
                        .HasColumnName("order_status_id");

                    b.Property<string>("PaperType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("paper_type");

                    b.Property<double>("Price")
                        .HasColumnType("float")
                        .HasColumnName("price");

                    b.Property<string>("PrintType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("print_type");

                    b.Property<DateOnly?>("RegistrationDate")
                        .HasColumnType("date")
                        .HasColumnName("registration_date");

                    b.Property<DateTime?>("UpdateDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("update_date_time");

                    b.HasKey("OrderId")
                        .HasName("PK__PrintOrd__46596229906EE16E");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("OrderStatusId");

                    b.HasIndex(new[] { "Number" }, "UQ__PrintOrd__FD291E41EC5F3387")
                        .IsUnique();

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("PublishingHouse.DAL.Model.Production", b =>
                {
                    b.Property<int>("ProductionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("production_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductionId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("address");

                    b.Property<int>("CityId")
                        .HasColumnType("int")
                        .HasColumnName("city_id");

                    b.Property<DateTime?>("CreateDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("create_date_time")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("ProductionTypeId")
                        .HasColumnType("int")
                        .HasColumnName("production_type_id");

                    b.Property<DateTime?>("UpdateDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("update_date_time");

                    b.HasKey("ProductionId")
                        .HasName("PK__Producti__60F4D65C9377E19B");

                    b.HasIndex("CityId");

                    b.HasIndex("ProductionTypeId");

                    b.ToTable("Production", (string)null);

                    b.HasData(
                        new
                        {
                            ProductionId = 1,
                            Address = "123 Main St",
                            CityId = 1,
                            CreateDateTime = new DateTime(2024, 12, 4, 21, 45, 12, 668, DateTimeKind.Utc).AddTicks(2851),
                            ProductionTypeId = 1
                        },
                        new
                        {
                            ProductionId = 2,
                            Address = "456 Elm St",
                            CityId = 2,
                            CreateDateTime = new DateTime(2024, 12, 4, 21, 45, 12, 668, DateTimeKind.Utc).AddTicks(3238),
                            ProductionTypeId = 1
                        },
                        new
                        {
                            ProductionId = 3,
                            Address = "789 Oak St",
                            CityId = 1,
                            CreateDateTime = new DateTime(2024, 12, 4, 21, 45, 12, 668, DateTimeKind.Utc).AddTicks(3240),
                            ProductionTypeId = 2
                        },
                        new
                        {
                            ProductionId = 4,
                            Address = "101 Pine St",
                            CityId = 3,
                            CreateDateTime = new DateTime(2024, 12, 4, 21, 45, 12, 668, DateTimeKind.Utc).AddTicks(3241),
                            ProductionTypeId = 2
                        },
                        new
                        {
                            ProductionId = 5,
                            Address = "202 Maple St",
                            CityId = 3,
                            CreateDateTime = new DateTime(2024, 12, 4, 21, 45, 12, 668, DateTimeKind.Utc).AddTicks(3242),
                            ProductionTypeId = 1
                        });
                });

            modelBuilder.Entity("PublishingHouse.DAL.Model.ProductionType", b =>
                {
                    b.Property<int>("ProductionTypeId")
                        .HasColumnType("int")
                        .HasColumnName("production_type_id");

                    b.Property<DateTime?>("CreateDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("create_date_time")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdateDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("update_date_time");

                    b.HasKey("ProductionTypeId")
                        .HasName("PK__Producti__27977FA8C05506DA");

                    b.HasIndex(new[] { "Name" }, "UQ__Producti__72E12F1B949AE5C2")
                        .IsUnique()
                        .HasFilter("[name] IS NOT NULL");

                    b.ToTable("ProductionType", (string)null);

                    b.HasData(
                        new
                        {
                            ProductionTypeId = 1,
                            CreateDateTime = new DateTime(2024, 12, 4, 21, 45, 12, 669, DateTimeKind.Utc).AddTicks(5436),
                            Name = "Printing"
                        },
                        new
                        {
                            ProductionTypeId = 2,
                            CreateDateTime = new DateTime(2024, 12, 4, 21, 45, 12, 669, DateTimeKind.Utc).AddTicks(5891),
                            Name = "Binding"
                        });
                });

            modelBuilder.Entity("PublishingHouse.DAL.Model.QualityMark", b =>
                {
                    b.Property<int>("QualityMarkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("quality_mark_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QualityMarkId"));

                    b.Property<DateTime?>("CreateDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("create_date_time")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdateDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("update_date_time");

                    b.HasKey("QualityMarkId")
                        .HasName("PK__QualityM__F1D96A9EC050D447");

                    b.HasIndex(new[] { "Name" }, "UQ__QualityM__72E12F1B83341E29")
                        .IsUnique()
                        .HasFilter("[name] IS NOT NULL");

                    b.ToTable("QualityMark", (string)null);

                    b.HasData(
                        new
                        {
                            QualityMarkId = 1,
                            CreateDateTime = new DateTime(2024, 12, 4, 21, 45, 12, 670, DateTimeKind.Utc).AddTicks(7000),
                            Name = "Excellent"
                        },
                        new
                        {
                            QualityMarkId = 2,
                            CreateDateTime = new DateTime(2024, 12, 4, 21, 45, 12, 670, DateTimeKind.Utc).AddTicks(7377),
                            Name = "High"
                        },
                        new
                        {
                            QualityMarkId = 3,
                            CreateDateTime = new DateTime(2024, 12, 4, 21, 45, 12, 670, DateTimeKind.Utc).AddTicks(7378),
                            Name = "Moderate"
                        },
                        new
                        {
                            QualityMarkId = 4,
                            CreateDateTime = new DateTime(2024, 12, 4, 21, 45, 12, 670, DateTimeKind.Utc).AddTicks(7380),
                            Name = "Defective"
                        });
                });

            modelBuilder.Entity("PublishingHouse.DAL.Model.Region", b =>
                {
                    b.Property<int>("RegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("region_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegionId"));

                    b.Property<DateTime?>("CreateDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("create_date_time")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdateDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("update_date_time");

                    b.HasKey("RegionId")
                        .HasName("PK__Region__01146BAE16614F6D");

                    b.HasIndex(new[] { "Name" }, "UQ__Region__72E12F1BB9D45034")
                        .IsUnique()
                        .HasFilter("[name] IS NOT NULL");

                    b.ToTable("Region", (string)null);

                    b.HasData(
                        new
                        {
                            RegionId = 1,
                            CreateDateTime = new DateTime(2024, 12, 4, 21, 45, 12, 672, DateTimeKind.Utc).AddTicks(1251),
                            Name = "North Region"
                        },
                        new
                        {
                            RegionId = 2,
                            CreateDateTime = new DateTime(2024, 12, 4, 21, 45, 12, 672, DateTimeKind.Utc).AddTicks(1650),
                            Name = "South Region"
                        });
                });

            modelBuilder.Entity("PublishingHouse.DAL.Model.BatchPrint", b =>
                {
                    b.HasOne("PublishingHouse.DAL.Model.PrintOrder", "Order")
                        .WithMany("BatchPrints")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK__BatchPrin__updat__01D345B0");

                    b.HasOne("PublishingHouse.DAL.Model.QualityMark", "QualityMark")
                        .WithMany("BatchPrints")
                        .HasForeignKey("QualityMarkId")
                        .IsRequired()
                        .HasConstraintName("FK__BatchPrin__quali__02C769E9");

                    b.Navigation("Order");

                    b.Navigation("QualityMark");
                });

            modelBuilder.Entity("PublishingHouse.DAL.Model.City", b =>
                {
                    b.HasOne("PublishingHouse.DAL.Model.Region", "Region")
                        .WithMany("Cities")
                        .HasForeignKey("RegionId")
                        .IsRequired()
                        .HasConstraintName("FK__City__update_dat__531856C7");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("PublishingHouse.DAL.Model.Customer", b =>
                {
                    b.HasOne("PublishingHouse.DAL.Model.CustomerType", "CustomerType")
                        .WithMany("Customers")
                        .HasForeignKey("CustomerTypeId")
                        .IsRequired()
                        .HasConstraintName("FK__Customer__update__72910220");

                    b.Navigation("CustomerType");
                });

            modelBuilder.Entity("PublishingHouse.DAL.Model.Employee", b =>
                {
                    b.HasOne("PublishingHouse.DAL.Model.Position", "Position")
                        .WithMany("Employees")
                        .HasForeignKey("PositionId")
                        .IsRequired()
                        .HasConstraintName("FK__Employee__update__5CA1C101");

                    b.HasOne("PublishingHouse.DAL.Model.Production", "Production")
                        .WithMany("Employees")
                        .HasForeignKey("ProductionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Employee__produc__5D95E53A");

                    b.Navigation("Position");

                    b.Navigation("Production");
                });

            modelBuilder.Entity("PublishingHouse.DAL.Model.OrderBook", b =>
                {
                    b.HasOne("PublishingHouse.DAL.Model.Book", "Book")
                        .WithMany("OrderBooks")
                        .HasForeignKey("BookId")
                        .IsRequired()
                        .HasConstraintName("FK__OrderBook__book___0880433F");

                    b.HasOne("PublishingHouse.DAL.Model.PrintOrder", "Order")
                        .WithMany("OrderBooks")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK__OrderBook__updat__078C1F06");

                    b.Navigation("Book");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("PublishingHouse.DAL.Model.OrderRequest", b =>
                {
                    b.HasOne("PublishingHouse.DAL.Model.Customer", "Customer")
                        .WithMany("OrderRequests")
                        .HasForeignKey("CustomerId")
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("PublishingHouse.DAL.Model.PrintOrder", b =>
                {
                    b.HasOne("PublishingHouse.DAL.Model.Customer", "Customer")
                        .WithMany("PrintOrders")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK__PrintOrde__custo__7A3223E8");

                    b.HasOne("PublishingHouse.DAL.Model.Employee", "Employee")
                        .WithMany("PrintOrders")
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK__PrintOrde__emplo__7B264821");

                    b.HasOne("PublishingHouse.DAL.Model.OrderStatus", "OrderStatus")
                        .WithMany("PrintOrders")
                        .HasForeignKey("OrderStatusId")
                        .IsRequired()
                        .HasConstraintName("FK__PrintOrde__updat__793DFFAF");

                    b.Navigation("Customer");

                    b.Navigation("Employee");

                    b.Navigation("OrderStatus");
                });

            modelBuilder.Entity("PublishingHouse.DAL.Model.Production", b =>
                {
                    b.HasOne("PublishingHouse.DAL.Model.City", "City")
                        .WithMany("Productions")
                        .HasForeignKey("CityId")
                        .IsRequired()
                        .HasConstraintName("FK__Productio__city___57DD0BE4");

                    b.HasOne("PublishingHouse.DAL.Model.ProductionType", "ProductionType")
                        .WithMany("Productions")
                        .HasForeignKey("ProductionTypeId")
                        .IsRequired()
                        .HasConstraintName("FK__Productio__updat__56E8E7AB");

                    b.Navigation("City");

                    b.Navigation("ProductionType");
                });

            modelBuilder.Entity("PublishingHouse.DAL.Model.Book", b =>
                {
                    b.Navigation("OrderBooks");
                });

            modelBuilder.Entity("PublishingHouse.DAL.Model.City", b =>
                {
                    b.Navigation("Productions");
                });

            modelBuilder.Entity("PublishingHouse.DAL.Model.Customer", b =>
                {
                    b.Navigation("OrderRequests");

                    b.Navigation("PrintOrders");
                });

            modelBuilder.Entity("PublishingHouse.DAL.Model.CustomerType", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("PublishingHouse.DAL.Model.Employee", b =>
                {
                    b.Navigation("PrintOrders");
                });

            modelBuilder.Entity("PublishingHouse.DAL.Model.OrderStatus", b =>
                {
                    b.Navigation("PrintOrders");
                });

            modelBuilder.Entity("PublishingHouse.DAL.Model.Position", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("PublishingHouse.DAL.Model.PrintOrder", b =>
                {
                    b.Navigation("BatchPrints");

                    b.Navigation("OrderBooks");
                });

            modelBuilder.Entity("PublishingHouse.DAL.Model.Production", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("PublishingHouse.DAL.Model.ProductionType", b =>
                {
                    b.Navigation("Productions");
                });

            modelBuilder.Entity("PublishingHouse.DAL.Model.QualityMark", b =>
                {
                    b.Navigation("BatchPrints");
                });

            modelBuilder.Entity("PublishingHouse.DAL.Model.Region", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
